format_version: v1.0
type: UniqueComponent
attributes: {id: ebi}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: EBI_SMC_BAT_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_BAT_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_BAT_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_BAT_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: Boolean
    attributes: {id: EBI_SMC_CHIP_SELECT0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_DATA_BUS_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '1'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_DATA_BUS_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '1'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_DATA_BUS_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '1'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_DATA_BUS_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '1'}
  - type: Integer
    attributes: {id: EBI_SMC_NCS_WR_PULSE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '6'}
  - type: Integer
    attributes: {id: EBI_SMC_NCS_WR_SETUP_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_NWAIT_MODE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_NWAIT_MODE_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_NWAIT_MODE_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_NWAIT_MODE_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: Integer
    attributes: {id: EBI_SMC_NWE_CYCLE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '6'}
  - type: Integer
    attributes: {id: EBI_SMC_NWE_PULSE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Integer
    attributes: {id: EBI_SMC_NWE_SETUP_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '5'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_PS_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_PS_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_PS_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: KeyValueSet
    attributes: {id: EBI_SMC_PS_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '0'}
  - type: Boolean
    attributes: {id: EBI_SMC_READ_ENABLE_MODE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: 'false'}
  - type: Boolean
    attributes: {id: EBI_SMC_WRITE_ENABLE_MODE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: ebi_cs0}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_lcc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: EBI_CS}
- type: ElementPosition
  attributes: {x: '139', y: '549', id: ebi}
