format_version: v1.0
type: UniqueComponent
attributes: {id: tcc9}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: INTR_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_OTHER_IRQn}
  - type: String
    attributes: {id: PWM_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWMCallbackRegister}
  - type: String
    attributes: {id: PWM_GET_PERIOD_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWM32bitPeriodGet}
  - type: String
    attributes: {id: PWM_OUTPUT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWMPatternSet}
  - type: String
    attributes: {id: PWM_OUTPUT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWMPatternSet}
  - type: Hex
    attributes: {id: PWM_PATTERN_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: '119'}
  - type: Hex
    attributes: {id: PWM_PH_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: '7'}
  - type: String
    attributes: {id: PWM_PH_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9CHANNEL0}
  - type: String
    attributes: {id: PWM_PH_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9CHANNEL1}
  - type: String
    attributes: {id: PWM_PH_W}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9CHANNEL2}
  - type: String
    attributes: {id: PWM_SET_DUTY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWM32bitDutySet}
  - type: String
    attributes: {id: PWM_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWMStart}
  - type: String
    attributes: {id: PWM_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: TCC9_PWMStop}
  - type: File
    attributes: {id: TCC_CAPTURE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCC_CAPTURE_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: 'false'}
  - type: File
    attributes: {id: TCC_CAPTURE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TCC_COMPARE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCC_COMPARE_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: 'false'}
  - type: Comment
    attributes: {id: TCC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TCC_COMPARE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_EVCTRL_EVACT1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: '0'}
  - type: Integer
    attributes: {id: TCC_MODULE_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: '150000000'}
  - type: Combo
    attributes: {id: TCC_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: PWM}
  - type: File
    attributes: {id: TCC_PWM_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCC_PWM_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: 'false'}
  - type: File
    attributes: {id: TCC_PWM_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TCC_TIMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCC_TIMER_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: 'true'}
  - type: Long
    attributes: {id: TCC_TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc9, value: '150000'}
  - type: File
    attributes: {id: TCC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TCC9_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_lcc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Backlight}
- type: ElementPosition
  attributes: {x: '280', y: '215', id: tcc9}
